<?php

return [
    Webkul\Account\AccountPlugin::class,
    Webkul\Blog\BlogPlugin::class,
    Webkul\Chatter\ChatterPlugin::class,
    Webkul\Contact\ContactPlugin::class,
    Webkul\Employee\EmployeePlugin::class,
    Webkul\Inventory\InventoryPlugin::class,
    Webkul\Invoice\InvoicePlugin::class,
    // Webkul\Product\ProductPlugin::class,
    Webkul\Payment\PaymentPlugin::class,
    Webkul\Partner\PartnerPlugin::class,
    Webkul\Project\ProjectPlugin::class,
    Webkul\Purchase\PurchasePlugin::class,
    Webkul\Support\SupportPlugin::class,
    Webkul\Recruitment\RecruitmentPlugin::class,
    Webkul\Sale\SalePlugin::class,
    Webkul\Security\SecurityPlugin::class,
    Webkul\Field\FieldsPlugin::class,
    Webkul\Partner\PartnerPlugin::class,
    Webkul\TimeOff\TimeOffPlugin::class,
    Webkul\Timesheet\TimesheetPlugin::class,
    Webkul\Website\WebsitePlugin::class,
];
