<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    Webkul\Analytic\AnalyticServiceProvider::class,
    Webkul\Account\AccountServiceProvider::class,
    Webkul\Chatter\ChatterServiceProvider::class,
    Webkul\Contact\ContactServiceProvider::class,
    Webkul\Employee\EmployeeServiceProvider::class,
    Webkul\Support\SupportServiceProvider::class,
    Webkul\Field\FieldServiceProvider::class,
    Webkul\Inventory\InventoryServiceProvider::class,
    Webkul\Invoice\InvoiceServiceProvider::class,
    Webkul\Partner\PartnerServiceProvider::class,
    Webkul\Payment\PaymentServiceProvider::class,
    Webkul\Product\ProductServiceProvider::class,
    Webkul\Project\ProjectServiceProvider::class,
    Webkul\TableViews\TableViewsServiceProvider::class,
    Webkul\Recruitment\RecruitmentServiceProvider::class,
    Webkul\Sale\SaleServiceProvider::class,
    Webkul\Security\SecurityServiceProvider::class,
    Webkul\TimeOff\TimeOffServiceProvider::class,
    Webkul\Timesheet\TimesheetServiceProvider::class,
];
