<?php

namespace Webkul\Employee\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('employees_skills')->delete();

        $skills = [
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'French',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Spanish',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'English',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'German',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Filipino',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Arabic',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Bengali',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Mandarin Chinese',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Wu Chinese',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Hindi',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Russian',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Portuguese',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Indonesian',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Urdu',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Japanese',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Punjabi',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Javanese',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Telugu',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Turkish',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Korean',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 1,
                'name'               => 'Marathi',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Communication',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Teamwork',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Problem-Solving',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Time Management',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Critical Thinking',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Decision-Making',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Organizational',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Stress management',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Adaptability',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Conflict Management',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Leadership',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Creativity',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Resourcefulness',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Persuasion',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 2,
                'name'               => 'Openness to criticism',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Javascript',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Python',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'C/C++',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Android',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Hadoop',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Spark',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'React',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Django',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'RDMS',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'NoSQL',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Go',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Java',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Kotlin',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'PHP',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'C#',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Swift',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'R',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Ruby',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Matlab',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'TypeScript',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Scala',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'HTML',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'CSS',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Rust',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 3,
                'name'               => 'Perl',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Web Development',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Database Management',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Cloud computing',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Network administration',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Cybersecurity',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'DevOps',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Machine Learning (AI)',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Data analysis/visualization',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Agile and Scrum methodologies',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Mobile app development',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Project Management',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'System Administration (Linux, Windows)',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Virtualization and Containerization',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'IT support',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'IT infrastructure and architecture',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'IT service management (ITSM)',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'Big data technologies (Hadoop, Spark)',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'IoT and embedded systems',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 4,
                'name'               => 'IT governance and compliance (GDPR, HIPAA,...)',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'Communication',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'Analytics',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'Digital advertising',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'Public Speaking',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'CMS',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'sort'               => 10,
                'skill_type_id'      => 5,
                'name'               => 'Email Marketing',
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
        ];

        DB::table('employees_skills')->insert(collect($skills)->map(function ($skill) {
            $skill['creator_id'] = 1;

            return $skill;
        })->toArray());

        $this->call(SkillLevelSeeder::class);
    }
}
